CREATE TABLE users (
  user_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(150) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  createdAt DATETIME NOT NULL,
  updatedAt DATETIME NOT NULL
);

CREATE TABLE accessory (
  accessory_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  image_url VARCHAR(300) NOT NULL,
  user_id INT UNSIGNED NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE clothing (
  clothing_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  image_url VARCHAR(300) NOT NULL,
  user_id INT UNSIGNED NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE fits (
  fit_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  image_url VARCHAR(300) NOT NULL,
  user_id INT UNSIGNED NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE tags (
  tag_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  tag_name VARCHAR(150) NOT NULL,
  user_id INT UNSIGNED NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- Many-to-many

CREATE TABLE FitAccessories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  fit_id INT UNSIGNED NOT NULL,
  accessory_id INT UNSIGNED NOT NULL,
  FOREIGN KEY (fit_id) REFERENCES fits(fit_id),
  FOREIGN KEY (accessory_id) REFERENCES accessory(accessory_id)
);

CREATE TABLE FitClothing (
  id INT AUTO_INCREMENT PRIMARY KEY,
  fit_id INT UNSIGNED NOT NULL,
  clothing_id INT UNSIGNED NOT NULL,
  FOREIGN KEY (fit_id) REFERENCES fits(fit_id),
  FOREIGN KEY (clothing_id) REFERENCES clothing(clothing_id)
);

CREATE TABLE FitTags (
  id INT AUTO_INCREMENT PRIMARY KEY,
  fit_id INT UNSIGNED NOT NULL,
  tag_id INT UNSIGNED NOT NULL,
  FOREIGN KEY (fit_id) REFERENCES fits(fit_id),
  FOREIGN KEY (tag_id) REFERENCES tags(tag_id)
);

